// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChangeValueController from "./change_value_controller"
application.register("change-value", ChangeValueController)

import DishListingController from "./dish_listing_controller"
application.register("dish-listing", DishListingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemQuantityController from "./item_quantity_controller"
application.register("item-quantity", ItemQuantityController)

import MapController from "./map_controller"
application.register("map", MapController)

import MenuJumpController from "./menu_jump_controller"
application.register("menu-jump", MenuJumpController)

import ReservationFormController from "./reservation_form_controller"
application.register("reservation-form", ReservationFormController)

import ShoppingCartController from "./shopping_cart_controller"
application.register("shopping-cart", ShoppingCartController)
